use crate::error::BullShiftError;
use crate::trading::{Order, OrderSide, OrderType};
use chrono::{DateTime, Utc};
use serde::{Deserialize, Serialize};
use std::collections::HashMap;
use uuid::Uuid;

/// Algorithmic trading strategy types.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum AlgoStrategyType {
    /// Buy/sell based on moving average crossovers.
    MovingAverageCrossover,
    /// Mean reversion: trade when price deviates from historical mean.
    MeanReversion,
    /// Breakout: trade when price breaks support/resistance levels.
    Breakout,
    /// Volume-weighted average price execution.
    Vwap,
    /// Time-weighted average price execution.
    Twap,
    /// Grid trading: place orders at regular intervals.
    Grid,
    /// Trailing stop strategy.
    TrailingStop,
    /// Pairs trading: long/short correlated assets.
    PairsTrading,
    /// Custom strategy with user-defined logic.
    Custom(String),
}

impl std::fmt::Display for AlgoStrategyType {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::MovingAverageCrossover => write!(f, "MA Crossover"),
            Self::MeanReversion => write!(f, "Mean Reversion"),
            Self::Breakout => write!(f, "Breakout"),
            Self::Vwap => write!(f, "VWAP"),
            Self::Twap => write!(f, "TWAP"),
            Self::Grid => write!(f, "Grid"),
            Self::TrailingStop => write!(f, "Trailing Stop"),
            Self::PairsTrading => write!(f, "Pairs Trading"),
            Self::Custom(name) => write!(f, "Custom: {}", name),
        }
    }
}

/// State of an algo strategy execution.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub enum AlgoState {
    Idle,
    Running,
    Paused,
    Stopped,
    Error(String),
}

/// Parameters for an algo strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlgoParameters {
    /// Symbols to trade.
    pub symbols: Vec<String>,
    /// Maximum position size per symbol.
    pub max_position_size: f64,
    /// Maximum total exposure across all symbols.
    pub max_total_exposure: f64,
    /// Stop loss percentage (e.g., 0.02 = 2%).
    pub stop_loss_pct: Option<f64>,
    /// Take profit percentage.
    pub take_profit_pct: Option<f64>,
    /// Strategy-specific parameters.
    pub custom: HashMap<String, serde_json::Value>,
}

impl Default for AlgoParameters {
    fn default() -> Self {
        Self {
            symbols: Vec::new(),
            max_position_size: 1000.0,
            max_total_exposure: 10000.0,
            stop_loss_pct: Some(0.02),
            take_profit_pct: Some(0.05),
            custom: HashMap::new(),
        }
    }
}

/// A price data point for strategy evaluation.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct PriceBar {
    pub symbol: String,
    pub open: f64,
    pub high: f64,
    pub low: f64,
    pub close: f64,
    pub volume: f64,
    pub timestamp: DateTime<Utc>,
}

/// Signal generated by a strategy.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlgoSignal {
    pub id: Uuid,
    pub strategy_id: Uuid,
    pub symbol: String,
    pub side: OrderSide,
    pub strength: f64,
    pub suggested_quantity: f64,
    pub suggested_price: Option<f64>,
    pub reason: String,
    pub timestamp: DateTime<Utc>,
}

/// Performance metrics for a running strategy.
#[derive(Debug, Clone, Default, Serialize, Deserialize)]
pub struct AlgoPerformance {
    pub total_trades: usize,
    pub winning_trades: usize,
    pub losing_trades: usize,
    pub total_pnl: f64,
    pub max_drawdown: f64,
    pub sharpe_ratio: f64,
    pub win_rate: f64,
    pub avg_win: f64,
    pub avg_loss: f64,
    pub signals_generated: usize,
}

/// An algorithmic trading strategy instance.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AlgoStrategy {
    pub id: Uuid,
    pub name: String,
    pub strategy_type: AlgoStrategyType,
    pub parameters: AlgoParameters,
    pub state: AlgoState,
    pub performance: AlgoPerformance,
    pub created_at: DateTime<Utc>,
    pub started_at: Option<DateTime<Utc>>,
    pub last_signal: Option<DateTime<Utc>>,
}

/// Manages algorithmic trading strategies.
pub struct AlgoEngine {
    strategies: HashMap<Uuid, AlgoStrategy>,
    signals: std::collections::VecDeque<AlgoSignal>,
    price_history: HashMap<String, Vec<PriceBar>>,
    max_history: usize,
}

impl Default for AlgoEngine {
    fn default() -> Self {
        Self::new()
    }
}

impl AlgoEngine {
    pub fn new() -> Self {
        Self {
            strategies: HashMap::new(),
            signals: std::collections::VecDeque::with_capacity(1000),
            price_history: HashMap::new(),
            max_history: 500,
        }
    }

    /// Register a new algo strategy.
    pub fn add_strategy(
        &mut self,
        name: &str,
        strategy_type: AlgoStrategyType,
        parameters: AlgoParameters,
    ) -> Uuid {
        let id = Uuid::new_v4();
        let strategy = AlgoStrategy {
            id,
            name: name.to_string(),
            strategy_type,
            parameters,
            state: AlgoState::Idle,
            performance: AlgoPerformance::default(),
            created_at: Utc::now(),
            started_at: None,
            last_signal: None,
        };
        self.strategies.insert(id, strategy);
        id
    }

    /// Remove a strategy (must be stopped first).
    pub fn remove_strategy(&mut self, id: &Uuid) -> Result<(), BullShiftError> {
        let state = self
            .strategies
            .get(id)
            .map(|s| s.state.clone())
            .ok_or_else(|| BullShiftError::Trading(format!("Strategy {} not found", id)))?;

        if state == AlgoState::Running {
            return Err(BullShiftError::Trading(
                "Cannot remove a running strategy. Stop it first.".to_string(),
            ));
        }
        self.strategies.remove(id);
        Ok(())
    }

    /// Start a strategy.
    pub fn start_strategy(&mut self, id: &Uuid) -> Result<(), BullShiftError> {
        let strategy = self
            .strategies
            .get_mut(id)
            .ok_or_else(|| BullShiftError::Trading(format!("Strategy {} not found", id)))?;

        if strategy.parameters.symbols.is_empty() {
            return Err(BullShiftError::Validation(
                "Strategy must have at least one symbol".to_string(),
            ));
        }

        strategy.state = AlgoState::Running;
        strategy.started_at = Some(Utc::now());
        Ok(())
    }

    /// Pause a running strategy.
    pub fn pause_strategy(&mut self, id: &Uuid) -> Result<(), BullShiftError> {
        let strategy = self
            .strategies
            .get_mut(id)
            .ok_or_else(|| BullShiftError::Trading(format!("Strategy {} not found", id)))?;

        if strategy.state != AlgoState::Running {
            return Err(BullShiftError::Trading("Strategy is not running".to_string()));
        }
        strategy.state = AlgoState::Paused;
        Ok(())
    }

    /// Stop a strategy.
    pub fn stop_strategy(&mut self, id: &Uuid) -> Result<(), BullShiftError> {
        let strategy = self
            .strategies
            .get_mut(id)
            .ok_or_else(|| BullShiftError::Trading(format!("Strategy {} not found", id)))?;

        strategy.state = AlgoState::Stopped;
        Ok(())
    }

    /// Get a strategy by ID.
    pub fn get_strategy(&self, id: &Uuid) -> Option<&AlgoStrategy> {
        self.strategies.get(id)
    }

    /// List all strategies.
    pub fn list_strategies(&self) -> Vec<&AlgoStrategy> {
        self.strategies.values().collect()
    }

    /// Feed a new price bar into the engine and evaluate running strategies.
    pub fn on_price_update(&mut self, bar: PriceBar) -> Vec<AlgoSignal> {
        // Store price history
        let history = self
            .price_history
            .entry(bar.symbol.clone())
            .or_default();
        history.push(bar.clone());
        if history.len() > self.max_history {
            history.drain(..history.len() - self.max_history);
        }

        // Evaluate all running strategies for this symbol
        let mut new_signals = Vec::new();
        let strategy_ids: Vec<Uuid> = self
            .strategies
            .values()
            .filter(|s| {
                s.state == AlgoState::Running && s.parameters.symbols.contains(&bar.symbol)
            })
            .map(|s| s.id)
            .collect();

        for sid in strategy_ids {
            let history_clone = self.price_history.get(&bar.symbol).cloned().unwrap_or_default();
            if let Some(strategy) = self.strategies.get(&sid) {
                if let Some(signal) = evaluate_strategy(strategy, &bar, &history_clone) {
                    new_signals.push(signal);
                }
            }
        }

        // Record signals and update strategy metadata
        for signal in &new_signals {
            if let Some(strategy) = self.strategies.get_mut(&signal.strategy_id) {
                strategy.performance.signals_generated += 1;
                strategy.last_signal = Some(signal.timestamp);
            }
            if self.signals.len() >= 1000 {
                self.signals.pop_front();
            }
            self.signals.push_back(signal.clone());
        }

        new_signals
    }

    /// Convert a signal into an order.
    pub fn signal_to_order(&self, signal: &AlgoSignal) -> Order {
        let order_type = if signal.suggested_price.is_some() {
            OrderType::Limit
        } else {
            OrderType::Market
        };

        let now = Utc::now();
        Order {
            id: Uuid::new_v4(),
            symbol: signal.symbol.clone(),
            side: signal.side.clone(),
            quantity: signal.suggested_quantity,
            order_type,
            price: signal.suggested_price,
            stop_loss: None,
            take_profit: None,
            status: crate::trading::OrderStatus::Pending,
            created_at: now,
            updated_at: now,
        }
    }

    /// Record a trade result for performance tracking.
    pub fn record_trade_result(
        &mut self,
        strategy_id: &Uuid,
        pnl: f64,
    ) -> Result<(), BullShiftError> {
        let strategy = self
            .strategies
            .get_mut(strategy_id)
            .ok_or_else(|| BullShiftError::Trading(format!("Strategy {} not found", strategy_id)))?;

        strategy.performance.total_trades += 1;
        strategy.performance.total_pnl += pnl;

        if pnl > 0.0 {
            strategy.performance.winning_trades += 1;
            strategy.performance.avg_win = (strategy.performance.avg_win
                * (strategy.performance.winning_trades - 1) as f64
                + pnl)
                / strategy.performance.winning_trades as f64;
        } else if pnl < 0.0 {
            strategy.performance.losing_trades += 1;
            strategy.performance.avg_loss = (strategy.performance.avg_loss
                * (strategy.performance.losing_trades - 1) as f64
                + pnl.abs())
                / strategy.performance.losing_trades as f64;
        }

        if strategy.performance.total_trades > 0 {
            strategy.performance.win_rate =
                strategy.performance.winning_trades as f64 / strategy.performance.total_trades as f64;
        }

        // Update max drawdown
        if pnl < 0.0 && pnl.abs() > strategy.performance.max_drawdown {
            strategy.performance.max_drawdown = pnl.abs();
        }

        Ok(())
    }

    /// Get recent signals.
    pub fn recent_signals(&self, limit: usize) -> Vec<&AlgoSignal> {
        self.signals.iter().rev().take(limit).collect()
    }

    /// Get price history for a symbol.
    pub fn get_price_history(&self, symbol: &str) -> Option<&Vec<PriceBar>> {
        self.price_history.get(symbol)
    }
}

/// Evaluate a strategy against current price data and history.
fn evaluate_strategy(
    strategy: &AlgoStrategy,
    current_bar: &PriceBar,
    history: &[PriceBar],
) -> Option<AlgoSignal> {
    match strategy.strategy_type {
        AlgoStrategyType::MovingAverageCrossover => {
            evaluate_ma_crossover(strategy, current_bar, history)
        }
        AlgoStrategyType::MeanReversion => evaluate_mean_reversion(strategy, current_bar, history),
        AlgoStrategyType::Breakout => evaluate_breakout(strategy, current_bar, history),
        AlgoStrategyType::TrailingStop => evaluate_trailing_stop(strategy, current_bar, history),
        AlgoStrategyType::Grid => evaluate_grid(strategy, current_bar, history),
        _ => None, // VWAP, TWAP, PairsTrading, Custom require more context
    }
}

fn evaluate_ma_crossover(
    strategy: &AlgoStrategy,
    bar: &PriceBar,
    history: &[PriceBar],
) -> Option<AlgoSignal> {
    let fast_period = strategy
        .parameters
        .custom
        .get("fast_period")
        .and_then(|v| v.as_u64())
        .unwrap_or(10) as usize;
    let slow_period = strategy
        .parameters
        .custom
        .get("slow_period")
        .and_then(|v| v.as_u64())
        .unwrap_or(30) as usize;

    if history.len() < slow_period + 2 {
        return None;
    }

    let closes: Vec<f64> = history.iter().map(|b| b.close).collect();
    let fast_ma = sma(&closes[closes.len() - fast_period..]);
    let slow_ma = sma(&closes[closes.len() - slow_period..]);

    let prev_fast = sma(&closes[closes.len() - fast_period - 1..closes.len() - 1]);
    let prev_slow = sma(&closes[closes.len() - slow_period - 1..closes.len() - 1]);

    // Bullish crossover
    if prev_fast <= prev_slow && fast_ma > slow_ma {
        return Some(AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: strategy.id,
            symbol: bar.symbol.clone(),
            side: OrderSide::Buy,
            strength: ((fast_ma - slow_ma) / slow_ma).min(1.0),
            suggested_quantity: strategy.parameters.max_position_size / bar.close,
            suggested_price: None,
            reason: format!(
                "MA crossover: fast({})={:.2} crossed above slow({})={:.2}",
                fast_period, fast_ma, slow_period, slow_ma
            ),
            timestamp: Utc::now(),
        });
    }

    // Bearish crossover
    if prev_fast >= prev_slow && fast_ma < slow_ma {
        return Some(AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: strategy.id,
            symbol: bar.symbol.clone(),
            side: OrderSide::Sell,
            strength: ((slow_ma - fast_ma) / slow_ma).min(1.0),
            suggested_quantity: strategy.parameters.max_position_size / bar.close,
            suggested_price: None,
            reason: format!(
                "MA crossover: fast({})={:.2} crossed below slow({})={:.2}",
                fast_period, fast_ma, slow_period, slow_ma
            ),
            timestamp: Utc::now(),
        });
    }

    None
}

fn evaluate_mean_reversion(
    strategy: &AlgoStrategy,
    bar: &PriceBar,
    history: &[PriceBar],
) -> Option<AlgoSignal> {
    let lookback = strategy
        .parameters
        .custom
        .get("lookback")
        .and_then(|v| v.as_u64())
        .unwrap_or(20) as usize;
    let threshold = strategy
        .parameters
        .custom
        .get("std_devs")
        .and_then(|v| v.as_f64())
        .unwrap_or(2.0);

    if history.len() < lookback {
        return None;
    }

    let closes: Vec<f64> = history[history.len() - lookback..].iter().map(|b| b.close).collect();
    let mean = sma(&closes);
    let std_dev = std_deviation(&closes);

    if std_dev == 0.0 {
        return None;
    }

    let z_score = (bar.close - mean) / std_dev;

    if z_score < -threshold {
        // Price is below lower band — buy signal
        return Some(AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: strategy.id,
            symbol: bar.symbol.clone(),
            side: OrderSide::Buy,
            strength: (z_score.abs() / threshold - 1.0).clamp(0.1, 1.0),
            suggested_quantity: strategy.parameters.max_position_size / bar.close,
            suggested_price: Some(mean), // Target mean reversion
            reason: format!(
                "Mean reversion: z-score={:.2} (below -{:.1} std devs), mean={:.2}",
                z_score, threshold, mean
            ),
            timestamp: Utc::now(),
        });
    }

    if z_score > threshold {
        // Price is above upper band — sell signal
        return Some(AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: strategy.id,
            symbol: bar.symbol.clone(),
            side: OrderSide::Sell,
            strength: (z_score / threshold - 1.0).clamp(0.1, 1.0),
            suggested_quantity: strategy.parameters.max_position_size / bar.close,
            suggested_price: Some(mean),
            reason: format!(
                "Mean reversion: z-score={:.2} (above +{:.1} std devs), mean={:.2}",
                z_score, threshold, mean
            ),
            timestamp: Utc::now(),
        });
    }

    None
}

fn evaluate_breakout(
    strategy: &AlgoStrategy,
    bar: &PriceBar,
    history: &[PriceBar],
) -> Option<AlgoSignal> {
    let lookback = strategy
        .parameters
        .custom
        .get("lookback")
        .and_then(|v| v.as_u64())
        .unwrap_or(20) as usize;

    if history.len() < lookback {
        return None;
    }

    let recent = &history[history.len() - lookback..];
    let high = recent.iter().map(|b| b.high).fold(f64::NEG_INFINITY, f64::max);
    let low = recent.iter().map(|b| b.low).fold(f64::INFINITY, f64::min);

    if bar.close > high {
        return Some(AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: strategy.id,
            symbol: bar.symbol.clone(),
            side: OrderSide::Buy,
            strength: ((bar.close - high) / high).min(1.0),
            suggested_quantity: strategy.parameters.max_position_size / bar.close,
            suggested_price: None,
            reason: format!(
                "Breakout: price {:.2} broke above {}-bar high {:.2}",
                bar.close, lookback, high
            ),
            timestamp: Utc::now(),
        });
    }

    if bar.close < low {
        return Some(AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: strategy.id,
            symbol: bar.symbol.clone(),
            side: OrderSide::Sell,
            strength: ((low - bar.close) / low).min(1.0),
            suggested_quantity: strategy.parameters.max_position_size / bar.close,
            suggested_price: None,
            reason: format!(
                "Breakout: price {:.2} broke below {}-bar low {:.2}",
                bar.close, lookback, low
            ),
            timestamp: Utc::now(),
        });
    }

    None
}

fn evaluate_trailing_stop(
    strategy: &AlgoStrategy,
    bar: &PriceBar,
    history: &[PriceBar],
) -> Option<AlgoSignal> {
    let trail_pct = strategy
        .parameters
        .custom
        .get("trail_pct")
        .and_then(|v| v.as_f64())
        .unwrap_or(0.03);

    if history.len() < 5 {
        return None;
    }

    let recent_high = history
        .iter()
        .rev()
        .take(20)
        .map(|b| b.high)
        .fold(f64::NEG_INFINITY, f64::max);

    let stop_level = recent_high * (1.0 - trail_pct);

    if bar.close < stop_level {
        return Some(AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: strategy.id,
            symbol: bar.symbol.clone(),
            side: OrderSide::Sell,
            strength: ((stop_level - bar.close) / stop_level).min(1.0),
            suggested_quantity: strategy.parameters.max_position_size / bar.close,
            suggested_price: None,
            reason: format!(
                "Trailing stop: price {:.2} fell below {:.1}% trail from high {:.2} (stop={:.2})",
                bar.close,
                trail_pct * 100.0,
                recent_high,
                stop_level
            ),
            timestamp: Utc::now(),
        });
    }

    None
}

fn evaluate_grid(
    strategy: &AlgoStrategy,
    bar: &PriceBar,
    _history: &[PriceBar],
) -> Option<AlgoSignal> {
    let grid_size = strategy
        .parameters
        .custom
        .get("grid_size")
        .and_then(|v| v.as_f64())
        .unwrap_or(5.0);
    let base_price = strategy
        .parameters
        .custom
        .get("base_price")
        .and_then(|v| v.as_f64())
        .unwrap_or(bar.close);

    let distance = bar.close - base_price;
    let grid_levels = (distance / grid_size).abs();

    // Only signal at grid level boundaries
    if grid_levels >= 1.0 && (grid_levels % 1.0) < 0.1 {
        let side = if distance < 0.0 {
            OrderSide::Buy // Price dropped a grid level — buy
        } else {
            OrderSide::Sell // Price rose a grid level — sell
        };

        return Some(AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: strategy.id,
            symbol: bar.symbol.clone(),
            side,
            strength: 0.5,
            suggested_quantity: strategy.parameters.max_position_size / bar.close / 5.0,
            suggested_price: Some(bar.close),
            reason: format!(
                "Grid: price {:.2} at grid level {:.0} (size={:.2}, base={:.2})",
                bar.close, grid_levels, grid_size, base_price
            ),
            timestamp: Utc::now(),
        });
    }

    None
}

// --- Math helpers ---

fn sma(values: &[f64]) -> f64 {
    if values.is_empty() {
        return 0.0;
    }
    values.iter().sum::<f64>() / values.len() as f64
}

fn std_deviation(values: &[f64]) -> f64 {
    if values.len() < 2 {
        return 0.0;
    }
    let mean = sma(values);
    let variance = values.iter().map(|v| (v - mean).powi(2)).sum::<f64>() / values.len() as f64;
    variance.sqrt()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[allow(dead_code)]
    fn make_bars(symbol: &str, prices: &[f64]) -> Vec<PriceBar> {
        prices
            .iter()
            .map(|&p| PriceBar {
                symbol: symbol.to_string(),
                open: p,
                high: p * 1.01,
                low: p * 0.99,
                close: p,
                volume: 1000.0,
                timestamp: Utc::now(),
            })
            .collect()
    }

    #[test]
    fn test_add_and_list_strategies() {
        let mut engine = AlgoEngine::new();
        let params = AlgoParameters {
            symbols: vec!["AAPL".to_string()],
            ..Default::default()
        };
        engine.add_strategy("MA Cross", AlgoStrategyType::MovingAverageCrossover, params);
        assert_eq!(engine.list_strategies().len(), 1);
    }

    #[test]
    fn test_start_stop_strategy() {
        let mut engine = AlgoEngine::new();
        let params = AlgoParameters {
            symbols: vec!["AAPL".to_string()],
            ..Default::default()
        };
        let id = engine.add_strategy("test", AlgoStrategyType::Breakout, params);

        engine.start_strategy(&id).unwrap();
        assert_eq!(engine.get_strategy(&id).unwrap().state, AlgoState::Running);

        engine.pause_strategy(&id).unwrap();
        assert_eq!(engine.get_strategy(&id).unwrap().state, AlgoState::Paused);

        engine.stop_strategy(&id).unwrap();
        assert_eq!(engine.get_strategy(&id).unwrap().state, AlgoState::Stopped);
    }

    #[test]
    fn test_cannot_start_without_symbols() {
        let mut engine = AlgoEngine::new();
        let id = engine.add_strategy(
            "empty",
            AlgoStrategyType::MeanReversion,
            AlgoParameters::default(),
        );
        assert!(engine.start_strategy(&id).is_err());
    }

    #[test]
    fn test_cannot_remove_running() {
        let mut engine = AlgoEngine::new();
        let params = AlgoParameters {
            symbols: vec!["AAPL".to_string()],
            ..Default::default()
        };
        let id = engine.add_strategy("test", AlgoStrategyType::Grid, params);
        engine.start_strategy(&id).unwrap();
        assert!(engine.remove_strategy(&id).is_err());
    }

    #[test]
    fn test_ma_crossover_signal() {
        let mut engine = AlgoEngine::new();
        let mut params = AlgoParameters {
            symbols: vec!["AAPL".to_string()],
            ..Default::default()
        };
        params.custom.insert("fast_period".to_string(), serde_json::json!(3));
        params.custom.insert("slow_period".to_string(), serde_json::json!(5));

        let id = engine.add_strategy("MA", AlgoStrategyType::MovingAverageCrossover, params);
        engine.start_strategy(&id).unwrap();

        // Feed prices: declining then sharply rising (bullish crossover)
        let prices = vec![
            100.0, 99.0, 98.0, 97.0, 96.0, 95.0, 94.0, // declining
            100.0, 105.0, // sharp rise
        ];
        let mut signals = Vec::new();
        for p in prices {
            let bar = PriceBar {
                symbol: "AAPL".to_string(),
                open: p,
                high: p * 1.01,
                low: p * 0.99,
                close: p,
                volume: 1000.0,
                timestamp: Utc::now(),
            };
            signals.extend(engine.on_price_update(bar));
        }

        // Should have at least one signal from the crossover
        assert!(!signals.is_empty());
    }

    #[test]
    fn test_mean_reversion_signal() {
        let mut engine = AlgoEngine::new();
        let mut params = AlgoParameters {
            symbols: vec!["SPY".to_string()],
            ..Default::default()
        };
        params.custom.insert("lookback".to_string(), serde_json::json!(5));
        params.custom.insert("std_devs".to_string(), serde_json::json!(1.5));

        let id = engine.add_strategy("MR", AlgoStrategyType::MeanReversion, params);
        engine.start_strategy(&id).unwrap();

        // Stable prices then a big drop
        let prices = vec![100.0, 100.0, 100.0, 100.0, 100.0, 85.0];
        let mut signals = Vec::new();
        for p in prices {
            let bar = PriceBar {
                symbol: "SPY".to_string(),
                open: p,
                high: p,
                low: p,
                close: p,
                volume: 1000.0,
                timestamp: Utc::now(),
            };
            signals.extend(engine.on_price_update(bar));
        }

        assert!(!signals.is_empty());
        let signal = &signals[0];
        assert!(matches!(signal.side, OrderSide::Buy));
        assert!(signal.reason.contains("Mean reversion"));
    }

    #[test]
    fn test_record_trade_result() {
        let mut engine = AlgoEngine::new();
        let params = AlgoParameters {
            symbols: vec!["AAPL".to_string()],
            ..Default::default()
        };
        let id = engine.add_strategy("test", AlgoStrategyType::Breakout, params);

        engine.record_trade_result(&id, 500.0).unwrap();
        engine.record_trade_result(&id, -200.0).unwrap();
        engine.record_trade_result(&id, 300.0).unwrap();

        let perf = &engine.get_strategy(&id).unwrap().performance;
        assert_eq!(perf.total_trades, 3);
        assert_eq!(perf.winning_trades, 2);
        assert_eq!(perf.losing_trades, 1);
        assert!((perf.total_pnl - 600.0).abs() < 0.01);
        assert!((perf.win_rate - 2.0 / 3.0).abs() < 0.01);
    }

    #[test]
    fn test_signal_to_order() {
        let engine = AlgoEngine::new();
        let signal = AlgoSignal {
            id: Uuid::new_v4(),
            strategy_id: Uuid::new_v4(),
            symbol: "AAPL".to_string(),
            side: OrderSide::Buy,
            strength: 0.8,
            suggested_quantity: 10.0,
            suggested_price: None,
            reason: "test".to_string(),
            timestamp: Utc::now(),
        };

        let order = engine.signal_to_order(&signal);
        assert_eq!(order.symbol, "AAPL");
        assert_eq!(order.quantity, 10.0);
        assert!(matches!(order.order_type, OrderType::Market));
    }

    #[test]
    fn test_sma() {
        assert!((sma(&[1.0, 2.0, 3.0, 4.0, 5.0]) - 3.0).abs() < 0.001);
        assert_eq!(sma(&[]), 0.0);
    }

    #[test]
    fn test_std_deviation() {
        let vals = vec![2.0, 4.0, 4.0, 4.0, 5.0, 5.0, 7.0, 9.0];
        let sd = std_deviation(&vals);
        assert!((sd - 2.0).abs() < 0.1);
    }

    #[test]
    fn test_algo_strategy_type_display() {
        assert_eq!(AlgoStrategyType::MovingAverageCrossover.to_string(), "MA Crossover");
        assert_eq!(AlgoStrategyType::Vwap.to_string(), "VWAP");
        assert_eq!(
            AlgoStrategyType::Custom("My Algo".to_string()).to_string(),
            "Custom: My Algo"
        );
    }
}
